#  We are using AWS OpsWorks with RDS. The OpsWorks coobook
#  automatically replaces this file and adds settings for production.
#  These settings include the database name, host, user, and password..

development: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  port: 3306
  encoding: utf8
  database: kanji-meister_development
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1

test:
  <<: *default
  database: kanji-meister_test
